services:
  auth:
    env_file: develop.env
    build:
      dockerfile: docker/auth.Dockerfile
      context: .
    image: koh/auth
    container_name: auth
    expose:
      - 8081
    networks:
      - kafka-network
    volumes:
      - ./docker/jw.key:/root/.key/private.key
      - ./docker/jw.key.pub:/root/.key/public.key
    deploy:
      resources:
        limits:
          memory: 200M

networks:
  kafka-network:
    external: true
