package koh.service.auth.kafka;

public enum KafkaReqTopic {
    TOPIC_AUTH_LOGIN_REQUEST,
    TOPIC_AUTH_REGISTER_REQUEST,
    TOPIC_AUTH_REFRESH_REQUEST,
    TOPIC_AUTH_GUEST_REQUEST,
    TOPIC_MAIL_REGISTER_CONFIRMATION_REQUEST,
}
